teamsite/config/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    #path('common/',include('common.urls')),
    #path('', views.index, name='index'),
]

teamsite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail),
    path('question/', views.question, name='question'),
]

teamsite/common/models.py
from django.db import models

# Create your models here.

teamsite/pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    #제목 반환
    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

teamsite/common/views.py
from django.shortcuts import render

# Create your views here.

teamsite/pybo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm

from .models import Question


# Create your views here.

def index(request):
    question = Question.objects.all
    context = {'question': question}
    return render(request, 'pybo/main.html', context)

def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

#요청게시판
def question(requst):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)

#회원가입
#def registerPage(request):
#    form = UserCreationForm()
#    if request.method == "POST":
#        form = UserCreationForm(request.POST)
#        if form.is_valid():
#            form.save()
#            return redirect('login')
#    context={'form':form}
#    return render(request, 'accounts/register.html', context)

teamsite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <!-- 반응형 적용 -->
    <meta name="viewport"
          content="width=divice-width, initial-scale=1, shrink-to-fit=no">
    <!-- bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- 개발자가 만든 pybo CSS -->

    <title>vita GOD</title>
</head>
<body>
    <!-- 내비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 -->
    {% block content %}
    {% endblock %}
    <!-- 반드시 먼저 jQuery 자바스크립트 적용 -->
    <!-- <script src="{% static 'jquery-3.6.3.min.js' %}"></script>-->
    <!-- 그 다음 bootstrap 자바스크립트 적용 -->
    <!-- <script src="{% static 'bootstrap.min.js' %}"></script>-->
</body>
</html>

teamsite/templates/navbar.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Vita GOD</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>
<body>
    <!-- 내비게이션바 추가 -->
    <nav class="navbar navbar-expand-xl navbar-dark bg-warning border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'pybo:index' %}">
              <img src="./vita.png" alt="VitaGOD" width="30" height="24">
                </a>
                <!-- 서치바(검색바) -->
                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-light my-2 my-sm-0 bg-light text-warning" type="submit"><i class="bi bi-search"></i></i></button>
                </form>
            <!-- 햄버거바 -->
            <button class="navbar-toggler ml-auto" type="button" date-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbsarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">로그인</a>
                    </li>
                    <li>
                        <a class="nav-link" href="#">회원가입</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>
</html>

teamsite/templates/pybo/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid text-center">
  <div class="row">
    <div class="col-1 bg-danger">
      여백
    </div>
        <div class="row row-cols-6 w-75">
            <div class="col-lg bg-dark">상품</div>
            <div class="col-lg bg-info">가격랭킹</div>
            <div class="col-lg bg-primary">함유량랭킹</div>
            <div class="col-lg bg-secondary">요청게시판</div>
        </div>
    <div class="col-1 bg-danger" style="width: 150px">
      여백
    </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
</body>
</html>

teamsite/templates/pybo/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
</body>
</html>

teamsite/templates/pybo/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="/pybo/{{ question.id }}/">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}
</body>
</html>